version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: cicd/Dockerfile
    container_name: user-api-prod
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    restart: always