version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: cicd/Dockerfile
    container_name: user-api-dev
    ports:
      - "3000:3000"
    volumes:
      - ../src:/app/src
      - ../db:/app/db
    environment:
      - NODE_ENV=development