export enum ErrorType {
    NOT_FOUND = 'NOT_FOUND',
    ALREADY_EXISTS = 'ALREADY_EXISTS',
    PERMISSION = 'PERMISSION',
    INVALID_STATUS = 'INVALID_STATUS',
    NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
    UNKNOWN = 'UNKNOWN'
}